
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 04 22:11:02 CST 2023
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 22;
  public static final int Llave_c = 29;
  public static final int Op_booleano = 25;
  public static final int Llave_a = 28;
  public static final int If = 7;
  public static final int T_dato = 4;
  public static final int Else = 8;
  public static final int string = 15;
  public static final int Corchete_c = 31;
  public static final int Corchete_a = 30;
  public static final int While = 10;
  public static final int Division = 20;
  public static final int Int = 5;
  public static final int Cadena = 6;
  public static final int Parentesis_c = 27;
  public static final int Parentesis_a = 26;
  public static final int For = 11;
  public static final int EOF = 0;
  public static final int P_coma = 33;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Imprimir = 14;
  public static final int Tipo = 13;
  public static final int Op_atribucion = 23;
  public static final int ERROR = 36;
  public static final int Do = 9;
  public static final int Op_logico = 21;
  public static final int Identificador = 34;
  public static final int Resta = 18;
  public static final int Multiplicacion = 19;
  public static final int Op_incremento = 24;
  public static final int Numero = 35;
  public static final int Declaracion = 12;
  public static final int Suma = 17;
  public static final int Main = 32;
  public static final int Igual = 16;
  public static final int Comillas = 3;
}

